### ISSUE TITLE
Move MVP to crossplane x-generation

### ISSUE THREAD

**Issue by joshmue** [SovereignCloudStack/central-api#10]
https://github.com/crossplane-contrib/x-generation/issues/21 is closed, now.

Reevaluate switching to x-generation. If feasible, switch.

**Comment by joshmue** [comment]
`generate.yaml`'s would look somewhat like this:

```yaml
group: openstack.compute.scs.community
name: InstanceV2
version: v1beta1
provider:
  baseURL: https://raw.githubusercontent.com/crossplane-contrib/%s/%s/package/crds/%s
  name: provider-openstack
  version: v0.4.0
  crd:
    file: compute.openstack.crossplane.io_instancev2s.yaml
    version: v1alpha1
compositions:
  - name: xinstancev2.openstack.compute.scs.community
    provider: openstack
    default: true
overrideFieldsInClaim: []
usePipeline: true
additionalPipelineSteps: []
```
